name: API Gateway deployment

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
        inputs:
            branch:
                description: "Branch to use"
                required: true
                default: "main"

jobs:
    apiGatewayDeployment:
        name: "API Gateway Deployment"
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: .
        permissions:
            id-token: write
            contents: read
            pull-requests: write

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.branch }}

            - name: OpenAPI Generator
              uses: hatamiarash7/openapi-generator@v0.3.0
              with:
                  generator: openapi
                  openapi-file: ./openapi/openapi.json
                  output: ./openapi/.generated

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::202062340677:role/TechChallengeInfraDeployer
                  aws-region: ${{ vars.AWS_REGION }}

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  cli_config_credentials_token: ${{ secrets.TF_CLOUD_USER_API_TOKEN }}

            - name: Terraform Init
              run: terraform init
              working-directory: ./infra

            - name: Terraform Format
              run: terraform fmt -check
              working-directory: ./infra

            - name: Terraform Plan
              run: terraform plan -input=false
              working-directory: ./infra

            - name: Terraform Apply
              run: terraform apply -auto-approve -input=false -var-file=environment/prod.tfvars
              working-directory: ./infra
